In [1]:
from sklearn import datasets #importing datasets which is implimented in sklearn
from sklearn.model_selection import train_test_split 
import numpy as np
from sklearn import linear_model #linear regression model import

In [2]:
data=datasets.load_boston() #boston is file name 

In [3]:
print(data) 

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [4]:
import pandas as pd

In [5]:
dataframe=pd.DataFrame(data.data,columns=data.feature_names)

In [6]:
dataframe

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [7]:
pd.read_csv('C:\\Users\\SYED\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\boston_house_prices.csv')

506  13 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
0       CRIM  ZN      INDUS       CHAS        NOX         RM        AGE   
1    0.00632  18       2.31          0      0.538      6.575       65.2   
2    0.02731   0       7.07          0      0.469      6.421       78.9   
3    0.02729   0       7.07          0      0.469      7.185       61.1   
4    0.03237   0       2.18          0      0.458      6.998       45.8   
..       ...  ..        ...        ...        ...        ...        ...   
502  0.06263   0      11.93          0      0.573      6.593       69.1   
503  0.04527   0      11.93          0      0.573       6.12       76.7   
504  0.06076   0      11.93          0      0.573      6.976         91   
505  0.10959   0      11.93          0      0.573      6.794       89.3   
506  0.04741   0      11.93          0      0.573       6.03       80.8   

    Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12  \
0          DIS        RAD        TAX     PTRATIO           B       LSTAT   
1         4.09          1        296        15.3       396.9        4.98   
2       4.9671          2        242        17.8       396.9        9.14   
3       4.9671          2        242        17.8      392.83        4.03   
4       6.0622          3        222        18.7      394.63        2.94   
..         ...        ...        ...         ...         ...         ...   
502     2.4786          1        273          21      391.99        9.67   
503     2.2875          1        273          21       396.9        9.08   
504     2.1675          1        273          21       396.9        5.64   
505     2.3889          1        273          21      393.45        6.48   
506      2.505          1        273          21       396.9        7.88   

    Unnamed: 13  
0          MEDV  
1            24  
2          21.6  
3          34.7  
4          33.4  
..          ...  
502        22.4  
503        20.6  
504        23.9  
505          22  
506        11.9  

[507 rows x 14 columns]

In [8]:
x=data.data #deciding x and y
y=data.target

In [9]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [10]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [11]:
#spliting test and train data it will give 4 values so we need 4 variables to store 
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30)



In [12]:
xtest

array([[2.49800e-02, 0.00000e+00, 1.89000e+00, ..., 1.59000e+01,
        3.89960e+02, 8.65000e+00],
       [3.56868e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.93370e+02, 1.43600e+01],
       [4.30100e-02, 8.00000e+01, 1.91000e+00, ..., 2.20000e+01,
        3.82800e+02, 8.05000e+00],
       ...,
       [6.71772e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.20000e-01, 1.74400e+01],
       [1.52880e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.63020e+02, 2.32400e+01],
       [5.37200e-02, 0.00000e+00, 1.39200e+01, ..., 1.60000e+01,
        3.92850e+02, 7.39000e+00]])

In [13]:
#creating model object
model=linear_model.LinearRegression()

In [14]:
#train model
model.fit(xtrain,ytrain) #train machine according to data (find best fit line)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
#test model
p_values=model.predict(xtest) #predict values according to train data

In [16]:
p_values #predicted values

array([22.77597869, 22.82189999, 14.62790685, 20.87182153, 25.09578182,
       20.31373378, 15.25901408, 21.67334153, 13.78776563, 21.39530242,
       16.29616072,  5.47191427, 22.06996387, 27.14895196, 43.13332006,
       34.28795605, 25.26986687, 14.12681138, 20.97375386,  1.31289229,
       23.02080334, 25.51955884, 18.1944421 , 23.38906801,  7.63632235,
       32.8000577 , 17.18522899, 17.96239307, 20.81076012, 27.46737681,
       12.78807452, 20.06502156, 17.47791983, 21.64653712, 24.82805045,
       30.51581668, 27.48891513, 19.78589353, 23.47851281, 11.28546881,
       25.28857419, 24.81229701, -0.2629559 , 28.50062214, 17.84247629,
       23.8056151 , 20.26684647, 21.49413304, 27.11532288, 26.86856826,
       30.08067186, 19.2789872 , 25.0608688 , 21.36218472, 19.10532986,
       18.02745488, 38.41011795, 31.14949016, 16.29448785, 40.26644693,
       12.67657712, 37.39452203, 27.66932441, 40.71594946, 40.09160538,
       29.94704998, 28.64166582, 21.23010729, 16.39663126, 24.28

In [17]:
ytest #orignal ytest data

array([16.5, 23.2, 18.2, 16.7, 24.6, 21.8,  8.4, 21. , 14.3, 21. , 15.2,
       10.5, 16.1, 22.8, 50. , 37.9, 24.2, 13.4, 20.9, 17.9, 22.9, 25. ,
       17.5, 17.8,  7. , 36.4, 19.1,  7.2, 23.1, 22. , 13.6, 20.4, 17.4,
       19. , 22.2, 37. , 23.9, 18.5, 25. , 15.2, 24. , 20.7, 13.8, 22.5,
       22.5, 24.4, 18.3, 19.6, 22.6, 22. , 25.1, 18.9, 18.5, 24.1, 15.3,
       12.7, 37.6, 31.5, 17.8, 50. , 10.5, 50. , 23.7, 50. , 50. , 32.9,
       28.6, 22. , 13.8, 19.4, 30.5, 24.5, 19.4, 14.3, 23.2, 20.3, 24.4,
       16.6, 11.7, 23.4, 42.3, 17.1, 23.7, 31.1, 30.1, 25. , 22.2, 48.8,
        5. , 16.3, 23.8, 12. , 19.1, 23.9, 15. , 17.5, 17.1, 19.6, 33.4,
       24.7, 11.7,  8.8, 10.8, 19.3, 20.3, 48.5, 21.7, 23.8, 24.7, 21.5,
        7.4, 35.4, 23. , 19.7, 20.7, 50. , 13.4, 19.2, 33.8, 31.6, 13.3,
       17.8, 16.8, 11.5, 18.6, 14.1, 22.6, 27.5, 25. , 34.9, 21.2, 15.6,
       11.8,  9.6, 23.8, 14.5,  8.7, 18.4, 31.5, 20.2, 12.6, 15.6, 22.6,
       22.3, 50. , 22.2, 21.4, 11.8, 12.5, 13.4, 13

In [18]:
#accuracy check
accuracy=model.score(xtest,ytest)*100
print(accuracy)

71.77884611038981


In [19]:
import numpy as np
mean_square_error=np.mean((ytest-p_values)**2)
print(mean_square_error)

26.440658888708015
