In [1]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import train_test_split 
import numpy as np
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB #importing Gaussian model from Naive Bayes algorithem
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

In [2]:
dataset=load_iris()
x=dataset.data
y=dataset.target

In [3]:
#train and test data
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30)

In [4]:
#1) gaussian model
gnb_model=GaussianNB()
gnb_model.fit(xtrain,ytrain)
y_predict=gnb_model.predict(xtest)
accuracy=gnb_model.score(xtest,ytest)*100
print('accuracy',accuracy)


accuracy 97.77777777777777


In [5]:
#confusion matrix creation
cm=confusion_matrix(ytest,y_predict) # syntax of confusion matrix= variable=confusion_matrix(orignaldat,predicted data)
print(cm)


[[14  0  0]
 [ 0 12  0]
 [ 0  1 18]]


In [6]:
# 2) multinomial model
mn_model=MultinomialNB()
mn_model.fit(xtrain,ytrain)
y_mn_pred=mn_model.predict(xtest)
print(y_mn_pred)
accuracy1=mn_model.score(xtest,ytest)*100
print('accuracy',accuracy1)
print(ytest)

[1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 2 1 0 1 1 0 2 1 2
 1 1 1 1 1 1 1 0]
accuracy 64.44444444444444
[2 2 0 0 2 0 1 1 0 2 0 1 0 0 0 0 1 2 2 0 2 0 2 2 1 1 1 1 2 1 0 2 2 0 2 2 2
 2 1 2 2 1 1 2 0]


In [7]:
#confusion method for multinomial
cm1=confusion_matrix(ytest,y_mn_pred)
print(cm1)

[[14  0  0]
 [ 0 12  0]
 [ 0 16  3]]


In [8]:
# 3) Bernoulli method
b_model=BernoulliNB()
b_model.fit(xtrain,ytrain)
y_b_pred=b_model.predict(xtest)
print(y_b_pred)
accuracy2=b_model.score(xtest,ytest)*100
print('accuracy',accuracy2)
print(ytest)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]
accuracy 26.666666666666668
[2 2 0 0 2 0 1 1 0 2 0 1 0 0 0 0 1 2 2 0 2 0 2 2 1 1 1 1 2 1 0 2 2 0 2 2 2
 2 1 2 2 1 1 2 0]


In [9]:
#confusion method for Bernoulli
cm2=confusion_matrix(ytest,y_b_pred)
print(cm1)

[[14  0  0]
 [ 0 12  0]
 [ 0 16  3]]
